### ISSUE TITLE
Badges link to sgoudham/java

### ISSUE THREAD

**Issue by nekowinston** [sgoudham/trace#1]
Dear @sgoudham,

I was reviewing the README for your Java library and noticed that the badges included at the top of the document are linking to the wrong repository. As a user of this library, it is important that all information provided is accurate and up-to-date.

https://github.com/sgoudham/trace/blob/71c96e0009cf14827c9fd601059f522e9dbee3bc/README.md?plain=1#L1-L4

I kindly request that you update the links in the badges to point to the correct repository. This will ensure that users are able to access the relevant information and resources for this library.

Thank you for your time and attention to this matter. Please let me know if you have any questions or if there is anything else I can assist you with.

Sincerely,
@nekowinston

**Comment by sgoudham** [comment]
I apologize deeply for any confusion or inconvenience caused by the incorrect links in the badges of my library. I understand the importance of providing accurate and up-to-date information for users, and I am deeply sorry that this error occurred. I apologize for my previous response as it was a confusion on my part.

I want to extend my apologies to anyone who may have been affected by this mistake and assure you that steps have been taken to prevent this kind of error from happening in the future. I will make sure to update the links as soon as possible to point to the correct repository.

Once again, I apologize for any confusion or frustration this may have caused, and I truly appreciate your patience and understanding. Thank you for bringing this issue to my attention, @nekowinston, and for your help in identifying the correct repository. Thank you for being a user of my library and for your help in making it better.

Sincerely,
@sgoudham
